site_name: DevOps Docs
site_description: Documentations autour de la CI/CD et de Github
site_url: http://localhost
site_author: RoiVioli

repo_name: DokeyDoc/mkdocs
repo_url: https://github.com/DokeyDoc/mkdocs

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  language: 'fr'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.code.copy

nav:
  - Accueil: index.md  # Assurez-vous que ce fichier existe !
  - Github:
      - Les bases de Github: github-commands.md
      - Gestion de compte: github/account.md  
  - Docker:
      - Les bases Docker: docker/docker-basics.md  
      - Docker compose: docker/docker-compose.md

markdown_extensions:
  # - mdx_truly_sane_lists # pour l'indentation des listes imbriquées
  # - pymdownx.tabbed
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.magiclink
  # - pymdownx.saneheaders
  - pymdownx.smartsymbols
  # - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

plugins:
  - tags
  - search:
      prebuild_index: false
  - git-revision-date-localized:
      enable_creation_date: true

extra_css:
  - _assets/stylesheets/extra.css  # Assurez-vous que ce fichier existe !
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - _assets/javascript/tables.js  # Assurez-vous que ce fichier existe !

